In [1]:
# 导入下方要使用的所有包
import torch

In [2]:
x = torch.arange(12)
x.shape  # 访问张量沿每个轴的长度的形状
# output ： torch.size([12])
x.numel() # shape中所有元素的乘积
# output ： 12
x_change = x.reshape(3,4) # 改变张量的形状而不改变元素数量和元素值
x_change.shape
# output ： torch.Size([3, 4])
x_change.numel()
# output ： 12
# concatenate 连结
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
# dim 0->行拼接；1->列拼接
torch.cat((X,Y), dim=0), torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [3]:
'''
广播机制：
1、通过适当复制元素来扩展一个或两个数组，以便转换后，两张张量具有相同的形状
2、对生成的数组执行按元素操作
'''
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
# 这个常来说a和b是无法相加的，因为两者形状不同
# 但是通过广播机制将两个矩阵广播为一个更大的(3×2)矩阵中
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
# 对象之间的转换

# 1、NumPy张量和torch.tensor之间的转换
tensor_to_numpy = X.numpy()  # 
numpy_to_tensor = torch.tensor(tensor_to_numpy)
type(tensor_to_numpy),type(numpy_to_tensor)  
#(numpy.ndarray, torch.Tensor)

# 2、torch.tensor张量转换为python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)
# (tensor([3.5000]), 3.5, 3.5, 3)

(tensor([3.5000]), 3.5, 3.5, 3)

In [ ]:
# test
X,Y,X<Y,X>Y
# 结果相当于X和Y两个矩阵中的元素一一比较然后得到的矩阵
'''相当于对b进行了两次复制：
 第一次 1×5 形状的张量复制了4次，变成了 4×5
 第二次 1×4×5 形状的张量复制了3次，变成了3×4×5
'''
a = torch.randn(3,4,5)
b = torch.randn(1,1,5)
a,b
c = a+b
a,b,c,c.shape



(tensor([[[ 0.9387,  1.3575,  1.2813, -1.1938,  1.2134],
          [ 0.9903,  0.2554, -0.3218, -1.1311,  0.0639],
          [-1.8448,  1.8138, -1.2115, -1.4867, -0.8529],
          [-1.8742, -0.2416,  1.1394, -0.0515,  0.6300]],
 
         [[ 0.0535,  1.2370, -0.5079, -0.1438,  0.7099],
          [ 0.3023,  1.0615,  0.7231,  2.0954,  1.2098],
          [ 0.4697, -1.9280, -2.0332,  1.4453,  0.3711],
          [-0.0384,  1.7899, -0.1977,  0.1268,  0.4820]],
 
         [[-0.9686,  0.1897, -1.3356,  0.7590, -1.2000],
          [ 1.1444,  0.8568,  0.3709,  0.0058, -2.5356],
          [ 1.0141,  0.6353, -0.7941,  0.6439,  0.3138],
          [ 0.8281,  0.7327,  1.2315,  1.0969, -1.3624]]]),
 tensor([[[ 0.6881, -0.1953,  0.1263,  0.9729,  0.3475]]]),
 tensor([[[ 1.6268,  1.1622,  1.4075, -0.2210,  1.5609],
          [ 1.6784,  0.0601, -0.1955, -0.1582,  0.4114],
          [-1.1566,  1.6185, -1.0852, -0.5138, -0.5054],
          [-1.1861, -0.4368,  1.2657,  0.9214,  0.9775]],
 
         [[ 0.74